### ISSUE TITLE
[3] Make some on-prem options opt-out

### ISSUE THREAD

**Issue by vanneback** [elastisys/ck8s-cluster#11]
The default installation should include all services necessary.
* LB
* NFS
* Object storage

However users might have a data-center with their own services e.g. Load-balancer. If they want to use their more robust LB or object storage we should allow this by having the option to not use / create our service but just point to what ever sollution they have. For load-balancing and object-store (as long as its s3 compatible) this should not have any impact. For the storage i belive they should be able to use a custom block-storage even if we dont support the storage class. 

Then they could add their own storage class or send a request for it later (This would only affect the apps anyway).

**Comment by Xartos** [comment]
> Not really relevant here. Move to the appropriate repository.

I think it's at least partly relevant here. Since LBs, NFS nodes and (at least for now) buckets in object storage are provisioned here

**Comment by simonklb** [comment]
> > Not really relevant here. Move to the appropriate repository.
> 
> I think it's at least partly relevant here. Since LBs, NFS nodes and (at least for now) buckets in object storage are provisioned here

I don't think this is actually an issue, correct me if I'm wrong:
* NFS is currently provisioned by cloud-init in Exoscale Terraform only.
* "internal" LBs are only provisioned if you put machines in the `[loadbalancer]` group in the Ansible inventory.
* Object storage bucket provisioning, yes, but let's move it out instead of making it opt-out.

**Comment by vanneback** [comment]
Closing since not really relevant here anymore.
