### ISSUE TITLE
Allow specifying name for new node when replacing or cloning

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#15]
Currently the new node will get a UUID as name. This is nice from an automation perspective since we don't have to worry about name collisions. For a human operator however, it is not so easy to tell the difference between these UUIDs and they do not tell us anything about what type of node it is. Descriptive node names like `master-0`, `worker-high-mem-5` or similar are much easier to interpret.
For this reason I suggest that we add the ability to set the name of the new node when cloning or replacing a node.

It is already possible to achieve this manually by using `add` and `remove` instead of `clone` and `replace` but exposing this functionality at the higher level commands would simplify things.
I suggest using the same `--name` flag as with the `add` command, but it could also make sense to spell out that it is the name of the *new* node by using a flag like `--new-name` instead.

Definition of done:
It is possible to do the following:
- `ck8sctl replace <old-node-name> --name=<new-node-name>`
- `ck8sctl clone <old-node-name> --name=<new-node-name>`
The above commands should also work without the `--name` flag and then generate UUIDs as names.
Node names must be verified to be unique before any other action is taken.
The documentation for the flag should mention this limitation and specifically point out that you cannot replace a node with a new node using the same name (since both nodes will be in the cluster for a little while).

**Comment by simonklb** [comment]
While I think we should reason about the nodes more as cattle and less as pets I absolutely can see why that is not always an option. We have had discussions about using a [similar approach to Docker](https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go) for the naming to make the nodes a bit more distinguishable as well. :smile: 

Just out of curiousity, would this be less of an issue if `ck8sctl list` listed the machine size as well?

**Comment by lentzi90** [comment]
The docker approach would be cool! Although I still think we would like specific names in many cases. I admit that what I usually want to be in the name should already be in the labels of the node so it is some repetition. However, the node names are immediately visible in many cases when the labels are not. E.g. a pod was scheduled to node <name>. A real world example would be this:

We get an alert about some pod "running where it is not supposed to". This happens if we taint a node but some pod is already running there so the taint was not considered when it was scheduled. We may then want to check what node the pod is running on. With a simple `kubectl get pods -o wide` we can find out what nodes the pods in the relevant namespace is on and hopefully spot what the problem is if the node names are good. If they aren't, we need to describe the node to find out what the matter is.

I'm not sure about the `ck8sctl list`. To be honest I haven't really used it and I'm not sure when I would? Most of the time I will use the Kubernetes API since I may need Kubernetes specific information like what pods are running there or if it has disk pressure.

**Comment by simonklb** [comment]
The list command is relevant in the context of this CLI. When working with Kubernetes, kubectl will take precedence of course and I could see how getting metadata from the name itself might be useful. I'm just not sure that is a good thing to practice as it's going to be extremely tricky for large clusters with many nodes.

Right now let's make it possible to use "pet-names" for the machines. But let's keep "cattle-names" as a long term goal imo. If that means having to rework some of the other parts of the ck8s stack, that should still be worth it in the long run I think.

**Comment by lentzi90** [comment]
Maybe we could compromise a bit and have some meaningful prefix followed by a UUID, like pod names? :slightly_smiling_face: 

```
master-abc123
master-bca321
master-cba231
worker-large-123cba
worker-small-321abc
```
What do you think?

**Comment by simonklb** [comment]
One of the changes introduced recently was to remove the need to specify node type when for example cloning a node (e.g. before you had to run `ckctl clone master foo` now you only need to run `ckctl clone foo`. Adding the node type as the prefix for all machines will basically reintroduce that need.

My goal here is of course not to make life harder for you though. So if this is actually an issue let's find a good solution. :)

My vote would be on introducing `--name` to `clone` and `replace` so that it's an opt-in thing while defaulting to the "all machines are treated as cattle mentality" naming in the general case. That way we might find other ways to make nodes more cattle-like over time.

That would of course mean some extra mental gymnastics on the operator's part in that they will have to pick a name that is not already in use, but name uniqueness is also something we could fail early on, making name-picking less of a worry.

**Comment by lentzi90** [comment]
Yeah I agree adding `--name` is good enough for now at least. It's not so much the "node type" that I'm after though, it must be much more dynamic than that. Not so much individual pet nodes as groups of different cattle if you get what I mean? :smile: Like "cow" nodes and "chicken" nodes. The node type that we had was just master worker, right?

**Comment by simonklb** [comment]
Right! We have at some point briefly discussed supporting multiple kinds of node types which you could combine, like `worker,localstorage,ssd`. But yes, right now you only have worker and master (loadbalancer is a special case for safespring) and you can only specify one for each machine.

Working with groups of machines instead of just single machines would also be really neat. Would probably be able to utilize something like instance groups in AWS (and similar concepts in other cloud providers). First steps towards supporting autoscaling, although that would require us to automate the join procedure as well which a whole different topic. :smile: 

I would not be against introducing the concept of machine groups though, maybe just labeling groups of machines both in tfvars.json and in Kubernetes would be a nice stepping-stone, just not sure if it's highest on the prio list atm. However:
`ckctl add group_name node_type size`
`ckctl scale +8 group_name`
`ckctl replace group_name --concurrent 4 --image v1.18.12+ck8s1`
would be pretty cool :sunglasses:

**Comment by tordsson** [comment]
Deprecated by kubespray
