### ISSUE TITLE
[3] Generate manual cluster state for on-prem support

### ISSUE THREAD

**Issue by vanneback** [elastisys/ck8s-cluster#3]
To make it easier to structure the ansible inventory file it would be helpful for init to generate a template inventory file when using `on-prem` as cloud provider. The inventory file should have at least 3 nodes per cluster plus two nodes were one is for load-balancer and one for nfs. (If we want object store in its own node this will be needed aswell)?

Also update readme with new options and syntax for the inventory files.

**Comment by lentzi90** [comment]
Can you elaborate on what we want to accomplish here? What is the input and what is the output?
Are we talking about translating `infra.json` into `ansible_hosts_{wc|sc}.ini`? Or maybe some kind of template to help create `infra.json`?

**Comment by simonklb** [comment]
My idea would be to use the same client and API we do currently but without Terraform. So basically a cluster state that is hand-crafted instead of `terraform output` and the apply flow starts from after `terraform apply` is done in a normal deployment.

`infra.json` is today more used as some kind of transport between ck8s-cluster and other tools and never got much love in this project (mostly ad-hoc for legacy purposes). Perhaps we could re-introduce it but polish it up and give it a proper API type that can be used both for external and internal cluster state.

**Comment by lentzi90** [comment]
Ok I think I understand now. So this could be solved by implementing something like `renderAnsibleInventoryFromMetalConfig` [here](https://github.com/elastisys/ck8s-cluster/blob/master/client/ansibleinventory.go#L82) and then add some logic around when to run which method?
Do we need another format for the cluster state though? I mean, could we just hand craft the ansible inventory or do we need some other format that is rendered into the inventory? We could reformat the inventory into yaml if that makes it easier to handle and parse! :thinking:

**Comment by simonklb** [comment]
I think it would be best to let the code manage the Ansible inventory rendering for all providers, even the bare-metal case. What I think should be hand crafted is the `api.ClusterState` as this is what Terraform produces once it has finished it's job. See this function: https://github.com/elastisys/ck8s-cluster/blob/fb3110c7825b8e8558400daca4635f689e543a0f/client/cluster.go#L640-L642

I'm not sure on the implementation details yet, but probably switching in that function between using `client.TerraformOutput` and something like `client.LoadManualStateFromFile` could work.

**Comment by vanneback** [comment]
Closing since we decided to not implement this in the cluster repo but rather use another tool for it.
