### ISSUE TITLE
Handle errors during k8s resource cleanup

### ISSUE THREAD

**Issue by simonklb** [elastisys/ck8s-cluster#31]
When destroying a cluster we try to clean up k8s resources that creates cloud infrastructure here:
https://github.com/elastisys/ck8s-cluster/blob/2a50e90330faa06afc3a283bf22a1453daf7405c/client/cluster.go#L192-L202

We should either log or exit on any error that occurs there. Right now some of the errors are just ignored.

**Comment by lentzi90** [comment]
It may be worth checking how this was done previously in the `destroy.bash` script: https://github.com/elastisys/ck8s-apps/blob/master/bin/destroy.bash#L18
I'm a bit worried that just deleting all Pods won't help, since they will just be recreated. If there is some Pod mounting a volume, it cannot be deleted. I don't think the PVCs can be deleted while mounted either.

**Comment by lentzi90** [comment]
Just to confirm, I have now used this a few times on citycloud and it happened at least once that there were volumes left dangling.
I always get a timeout error just after it deletes the PVCs, like this:
```
error: timed out waiting for the condition on persistentvolumeclaims/data-opendistro-es-data-0
```
