### ISSUE TITLE
Create error for empty whitelisting

### ISSUE THREAD

**Issue by vanneback** [elastisys/ck8s-cluster#39]
`init` now leaves the whitelisting fields empty. This will create error late in runtime when trying to access ssh to set up cluster. 

Suggestions:
* Create check that gives early error when whitelisting is empty.
* Or generate default values for whitelisting in init.

**Comment by Xartos** [comment]
Wouldn't it be the same exact issue if you had some defaults? Since it must be to your IP. 
I agree to some extent, but I feel like this should be up to the user to configure. That's the purpose why we have a init step separate to the apply step, so that the user are able to set up the config correctly. 
But maybe adding a validation for an empty whitelist could make sense. Or is there a situation where you want to create a airtight cluster? Since you are able to talk to the nodes within the private network.

**Comment by vanneback** [comment]
You cant create a airtight one now right? If your computer is not inside the private network. Yea the generate doesnt make sense. But i think a validation check would be nice to catch that its empty earlier

**Comment by Xartos** [comment]
Maybe that's correct. But isn't this true for more stuff? like the number of worker nodes can't be zero. Should we validate all tfvars then? I totally see your point, but I feel like as we have set it up right now with different terraform "api" (variables.tf) for each cloud provider, it will be hard to maintain this in a good manner. Or I guess it's fine for now but if we start to support more providers and they start to have more and more differences it will be hard.
Then we should at least have one terraform module that all cloud providers are based on and then we can have some sane validation for one instead of 4.

**Comment by Xartos** [comment]
I now see that we actually have some validation in the go code. You can't have less that 1 master.
But I don't know. I feel like we would need to have a discussion about this some time. What parameters should we limit and what do we entrust to the user to fill in correctly.

**Comment by tordsson** [comment]
Deprecated by kubespray
