### ISSUE TITLE
Ssh breaks the terminal sometimes

### ISSUE THREAD

**Issue by lentzi90** [elastisys/ck8s-cluster#57]
The built in ssh command breaks my terminal often when doing things that produce a lot of output or "complex" output (e.g. `apt upgrade` or editing a file with `vi`). It results in weird behaviors like printing all output on the same line as the prompt (no newlines).

The problem could be related to my specific setup so I would be grateful if someone else could confirm it. I'm running the byobu terminal multiplexer and bash shell.

**Comment by simonklb** [comment]
Yea, we really should put some kind of `(experimental)` tag on that command. If you want a more consistent SSH shell use the SSH client installed on your OS dist instead of through the CLI.

We could also replace it with running `sops ... ssh-agent... ssh ...` instead of using the SSH package in go.

**Comment by Xartos** [comment]
I have this as a function in my `.bashrc` that I often use. Could be used as a temporary fix for now

```
function sops-ssh {
  SOPS_FILE=${1}
  shift
  sops exec-file --no-fifo ${SOPS_FILE} 'ssh -i {} '"${*}"
}
```

**Comment by tordsson** [comment]
Deprecated by kubespray
