### ISSUE TITLE
Ansible sometimes create two clusters

### ISSUE THREAD

**Issue by Xartos** [elastisys/ck8s-cluster#68]
If running apply with a new master that hasn't joined and the name of the new master is the first one in the ansible inventory (I think that is alphanumerically sorted) it will initialize that master in it's own cluster.

This is because when running apply, the `deploy-kubernetes` playbook is ran which uses `master[0] ` as the master to initialize. This will be the first one in the ansible inventory.

## Suggested solution

We should move this logic:

https://github.com/elastisys/ck8s-cluster/blob/48a5f2991a8611f966500e7cb0a6b7aa329949cd/ansible/join-cluster.yml#L6-L12

To an earlier step and only run initialize master if there's no active masters.

**Comment by simonklb** [comment]
Previously this was an issue for joining as well. This was solved with the logic above. Clearly this is an issue if you run `apply` with new master machine(s), but I think that was never intended and therefore overlooked.

Definitely needs to be fixed, but I'm just curious how you noticed it. Did you manually add new machines instead of using `add`, `clone` or `replace`?

**Comment by Xartos** [comment]
> Previously this was an issue for joining as well. This was solved with the logic above. Clearly this is an issue if you run `apply` with new master machine(s), but I think that was never intended and therefore overlooked.
> 
> Definitely needs to be fixed, but I'm just curious how you noticed it. Did you manually add new machines instead of using `add`, `clone` or `replace`?

I did a replace of a node, the replace failed (terraform timeout), so I ran apply again and terraform worked fine. But then when ansible, ran the issue appeared.

**Comment by tordsson** [comment]
Deprecated by kubespray
